'use strict';

const PDFDocument = require('pdfkit');
const fs = require('fs-extra');
const path = require('path');

const REPORTS_DIR = process.env.REPORTS_DIR ||
  path.join(process.env.TESTS_DIR ? path.dirname(process.env.TESTS_DIR) : path.resolve(__dirname, '../../'), 'reports');

const C = {
  navy:    '#1a1a2e',
  blue:    '#2c3e50',
  green:   '#27ae60',
  red:     '#e74c3c',
  orange:  '#e67e22',
  gray:    '#7f8c8d',
  lightBg: '#f8f9fa',
  rowAlt:  '#f0f4f8',
  white:   '#ffffff',
  text:    '#2d2d2d',
  border:  '#dce1e7',
};

function statusColor(status) {
  if (status === 'passed') return C.green;
  if (status === 'failed' || status === 'timedOut') return C.red;
  return C.orange;
}

function statusLabel(status) {
  if (status === 'passed') return 'Passed';
  if (status === 'failed') return 'Failed';
  if (status === 'timedOut') return 'Timeout';
  return 'Pending';
}

function getPriority(name) {
  const n = name.toLowerCase();
  if (n.includes('p0') || n.includes('critical') || n.includes('smoke')) return 'P0';
  if (n.includes('p1') || n.includes('high')) return 'P1';
  if (n.includes('p2') || n.includes('medium')) return 'P2';
  if (n.includes('p3') || n.includes('low')) return 'P3';
  return 'P2';
}

function drawSectionHeader(doc, text, y, W) {
  doc.fillColor(C.blue).rect(40, y, W, 22).fill();
  doc.fillColor(C.white).font('Helvetica-Bold').fontSize(10)
    .text(text, 48, y + 6, { width: W - 16 });
  doc.fillColor(C.text);
  return y + 22 + 8;
}

async function saveTestPdf({ testId, feature, url, fileName, createdAt, testResults, passed, total, success }) {
  await fs.ensureDir(REPORTS_DIR);
  const safeName = `${testId}_${feature.replace(/[^a-zA-Z0-9_а-яА-Я]/g, '_').slice(0, 50)}`;
  const pdfPath = path.join(REPORTS_DIR, `${safeName}.pdf`);

  const date = createdAt ? new Date(createdAt).toLocaleString('ru-RU') : new Date().toLocaleString('ru-RU');
  const hasResults = Array.isArray(testResults) && testResults.length > 0;
  const passedCount = passed != null ? passed : (hasResults ? testResults.filter(t => t.status === 'passed').length : null);
  const totalCount  = total  != null ? total  : (hasResults ? testResults.length : null);
  const failures = hasResults ? testResults.filter(t => t.status !== 'passed') : [];

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 40, size: 'A4' });
    const stream = fs.createWriteStream(pdfPath);
    doc.pipe(stream);

    const W = 515;
    let y = 40;

    // ── Header ──────────────────────────────────────────────────────────────
    doc.rect(40, y, W, 42).fill(C.navy);
    doc.fillColor(C.white).font('Helvetica-Bold').fontSize(18)
      .text('QA Test Report', 52, y + 12, { width: W - 20 });
    doc.fillColor(C.white).font('Helvetica').fontSize(8)
      .text('Generated by QA AI Agent', 52, y + 30, { width: 200 });
    y += 42 + 10;

    // ── Status bar ──────────────────────────────────────────────────────────
    const statusBg = success === true ? C.green : success === false ? C.red : C.orange;
    const statusText = success === true ? 'PASSED' : success === false ? 'FAILED' : 'PENDING';
    doc.rect(40, y, W, 28).fill(statusBg);
    doc.fillColor(C.white).font('Helvetica-Bold').fontSize(13)
      .text(statusText, 52, y + 7, { width: 120 });
    if (passedCount != null && totalCount != null) {
      doc.font('Helvetica').fontSize(11)
        .text(`${passedCount} / ${totalCount} tests passed`, 52 + 130, y + 8, { width: W - 200 });
    }
    y += 28 + 10;

    // ── Meta table ──────────────────────────────────────────────────────────
    const metaRows = [
      ['ID', testId],
      ['Feature', feature],
      ['URL', url || '—'],
      ['File', fileName || '—'],
      ['Date', date],
    ];
    const col0 = 80, col1 = W - 80;
    doc.font('Helvetica').fontSize(9);
    for (const [label, value] of metaRows) {
      doc.rect(40, y, col0, 18).fillAndStroke(C.lightBg, C.border);
      doc.rect(40 + col0, y, col1, 18).fillAndStroke(C.white, C.border);
      doc.fillColor(C.blue).font('Helvetica-Bold')
        .text(label, 44, y + 5, { width: col0 - 8 });
      doc.fillColor(C.text).font('Helvetica')
        .text(value, 44 + col0, y + 5, { width: col1 - 8, lineBreak: false });
      y += 18;
    }
    y += 12;

    // ── Description ─────────────────────────────────────────────────────────
    y = drawSectionHeader(doc, 'SCOPE OF TESTING', y, W);
    doc.rect(40, y, W, 40).fillAndStroke(C.lightBg, C.border);
    doc.fillColor(C.text).font('Helvetica').fontSize(9)
      .text(`Feature under test: ${feature}`, 48, y + 6, { width: W - 16 })
      .text(`Target URL: ${url || 'not specified'}`, 48, y + 18, { width: W - 16 })
      .text(`Test cases generated and executed automatically via Playwright (Chromium).`, 48, y + 30, { width: W - 16 });
    y += 40 + 10;

    // ── Test results table ───────────────────────────────────────────────────
    if (hasResults) {
      y = drawSectionHeader(doc, 'TEST RESULTS', y, W);

      // Table header
      const cols = [28, 310, 80, 60, 37];
      const headers = ['#', 'Test Name', 'Status', 'Priority', 'ms'];
      doc.rect(40, y, W, 18).fill(C.blue);
      doc.fillColor(C.white).font('Helvetica-Bold').fontSize(8);
      let x = 40;
      for (let i = 0; i < headers.length; i++) {
        doc.text(headers[i], x + 3, y + 5, { width: cols[i] - 4, lineBreak: false });
        x += cols[i];
      }
      y += 18;

      for (let i = 0; i < testResults.length; i++) {
        const t = testResults[i];
        const rowH = 16;

        if (y > 760) { doc.addPage(); y = 40; }

        const bg = i % 2 === 0 ? C.white : C.rowAlt;
        doc.rect(40, y, W, rowH).fillAndStroke(bg, C.border);

        x = 40;
        doc.fillColor(C.text).font('Helvetica').fontSize(7.5);

        // #
        doc.text(String(i + 1), x + 3, y + 4, { width: cols[0] - 4, lineBreak: false });
        x += cols[0];

        // Title
        const titleTrunc = t.title.length > 62 ? t.title.slice(0, 60) + '…' : t.title;
        doc.text(titleTrunc, x + 3, y + 4, { width: cols[1] - 6, lineBreak: false });
        x += cols[1];

        // Status with color
        doc.fillColor(statusColor(t.status)).font('Helvetica-Bold')
          .text(statusLabel(t.status), x + 3, y + 4, { width: cols[2] - 4, lineBreak: false });
        x += cols[2];

        // Priority
        doc.fillColor(C.text).font('Helvetica')
          .text(getPriority(t.title), x + 3, y + 4, { width: cols[3] - 4, lineBreak: false });
        x += cols[3];

        // Duration placeholder
        const dur = t.duration ? `${t.duration}` : '—';
        doc.text(dur, x + 3, y + 4, { width: cols[4] - 4, lineBreak: false });

        y += rowH;
      }
      y += 10;
    }

    // ── Failures detail ──────────────────────────────────────────────────────
    if (failures.length > 0) {
      if (y > 680) { doc.addPage(); y = 40; }
      y = drawSectionHeader(doc, 'FAILED TESTS — ROOT CAUSE', y, W);

      for (const t of failures) {
        if (y > 750) { doc.addPage(); y = 40; }

        doc.rect(40, y, W, 10).fill(C.red);
        doc.fillColor(C.white).font('Helvetica-Bold').fontSize(8)
          .text(t.title, 44, y + 1, { width: W - 8, lineBreak: false });
        y += 10;

        const errText = t.error ? t.error.replace(/\x1B\[[0-9;]*m/g, '').slice(0, 300) : 'No error details';
        const errLines = errText.split('\n').filter(l => l.trim()).slice(0, 4);
        const boxH = errLines.length * 11 + 8;
        doc.rect(40, y, W, boxH).fillAndStroke('#fff5f5', C.border);
        doc.fillColor(C.red).font('Courier').fontSize(7.5);
        for (let li = 0; li < errLines.length; li++) {
          doc.text(errLines[li], 46, y + 4 + li * 11, { width: W - 12, lineBreak: false });
        }
        y += boxH + 6;
      }
      y += 4;
    }

    // ── Summary stats ────────────────────────────────────────────────────────
    if (hasResults) {
      if (y > 720) { doc.addPage(); y = 40; }
      y = drawSectionHeader(doc, 'SUMMARY', y, W);

      const statCols = 4;
      const statW = Math.floor(W / statCols);
      const stats = [
        { label: 'Total', value: String(totalCount), color: C.blue },
        { label: 'Passed', value: String(passedCount), color: C.green },
        { label: 'Failed', value: String(failures.length), color: failures.length ? C.red : C.gray },
        { label: 'Pass Rate', value: totalCount ? `${Math.round(passedCount / totalCount * 100)}%` : '—', color: C.navy },
      ];
      for (let i = 0; i < stats.length; i++) {
        const sx = 40 + i * statW;
        doc.rect(sx, y, statW - 4, 40).fill(C.lightBg);
        doc.fillColor(stats[i].color).font('Helvetica-Bold').fontSize(20)
          .text(stats[i].value, sx, y + 4, { width: statW - 4, align: 'center' });
        doc.fillColor(C.gray).font('Helvetica').fontSize(8)
          .text(stats[i].label, sx, y + 27, { width: statW - 4, align: 'center' });
      }
      y += 48;
    }

    // ── Footer ───────────────────────────────────────────────────────────────
    doc.fillColor(C.gray).font('Helvetica').fontSize(7)
      .text(`QA AI Agent  |  ${date}  |  ${testId}`, 40, 800, { width: W, align: 'center' });

    doc.end();
    stream.on('finish', () => resolve(pdfPath));
    stream.on('error', reject);
  });
}

module.exports = { saveTestPdf, REPORTS_DIR };
