apiVersion: v1
kind: Secret
metadata:
  name: qa-bot-secret
  namespace: qa
type: Opaque
stringData:
  ANTHROPIC_API_KEY: "sk-ant-api03-ЗАМЕНИ_НА_СВОЙ"
  BOT_TOKEN: "ЗАМЕНИ_НА_СВОЙ"
  ALLOWED_USERS: "508381849"
